export enum Tag {
  Rush = 'Rush',
  Turtle = 'Turtle',
  Harassment = 'Harassment',
  Micro = 'Micro',
  Macro = 'Macro',
  AllIn = 'All-in',
  Defensive = 'Defensive',
  CQC = 'CQC',
  Light = 'Light',
  Heavy = 'Heavy',
  Artillery = 'Artillery',
  Air = 'Air',
  Meme = 'Meme',
  Spam = 'Spam',
  Ranked = 'Ranked',
  Team = 'Team',
  Para = 'Para',
  Meta = 'Meta',
  AntiMeta = 'Anti-Meta',
  OneVsOne = '1v1',
  TwoVsTwo = '2v2',
  ThreeVsThree = '3v3',
  FourVsFour = '4v4',
  TenVsTen = '10v10',
  Cheese = 'Cheese',
  Early = 'Early',
  Mid = 'Mid',
  Late = 'Late',
  SlowGrind = "Slow Grind",
  Helo = "Helo",
  PlayForKD = "Play for K/D",
}

const tags = Object.values(Tag);
export { tags };
