name: WarYes Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Transfer files via SSH to temporary directory
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist/
          target: ${{ env.WWW_DIR_DEPLOY }}

      - name: Replace live folder with temporary directory
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mv ${{ env.WWW_DIR }} ${{ env.WWW_DIR_OLD }} 
            mv ${{ env.WWW_DIR_DEPLOY }} ${{ env.WWW_DIR }}
