name: WarYes Production Deployment
run-name: Production Deployment 🚀
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    # - run: npm ci
    # - run: npm run build

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: WarYes
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host ${{secrets.SSH_HOST}}
            HostName ${{secrets.SSH_HOST}}
            User ${{secrets.SSH_USER}}
            IdentityFile ~/.ssh/WarYes

    - name: Deploy with rsync to temp
      run: scp ./dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.WWW_DIR_DEPLOY }}

    - name: Swap www dir with deploy
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mv ${{ env.WWW_DIR}} ${{ env.WWW_DIR_OLD }} && mv ${{ env.WWW_DIR_DEPLOY }} ${{ env.WWW_DIR }}"

    - name: Remove or archive old prod dir
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf ${{ env.WWW_DIR_OLD }}"
